### PR TITLE
Issue/525

### PR DESCRIPTION
**Pull request by Karbashevskyi**

### CODE REVIEW

**Comment by Karbashevskyi** [comment]
#525

**Comment by CyJanek-00** [comment]
there is en errors in the console 
`ERROR TypeError: Cannot read properties of undefined (reading 'firstTime')`


https://github.com/user-attachments/assets/14b19a33-130e-4e25-98cb-4be1ec42d68e

image

**Comment by CyJanek-00** [comment]
incorret title that's show as tooltip: 
image

**Comment by Karbashevskyi** [comment]
@CyJanek-00  fixed

**Review by CyJanek-00 — APPROVED** [review]

**Comment by CyJanek-00** [comment]
@Karbashevskyi  - for my part, I am prepared to close. 
@Bozonych - do you have any comments/question ?

**Pull request merged**
