### PR TITLE
merge develop into main - 16.10.2024

### PR DESCRIPTION
**Pull request by Karbashevskyi**

### CODE REVIEW

**Comment by CyJanek-00** [comment]
there is something wrong when i delete an order 
i have 4 order on the calender, 
i go into order module and delete one of them, page have been reload and i expected to have 3 order on that page, but after deletion page presented 6 order

https://github.com/user-attachments/assets/fa1077b9-8b5e-4cd1-88f2-0e94bf7d5d1f

**Comment by CyJanek-00** [comment]
calendar grid does not adjust the width dynamically: 

https://github.com/user-attachments/assets/876134d1-b2d5-420a-a2e1-2800c081f493

**Comment by CyJanek-00** [comment]
edition of the order - whac-a-mole clipboard not disappear

https://github.com/user-attachments/assets/f493249e-d37f-48b0-92ad-46aff4927f3d

**Comment by Karbashevskyi** [comment]
> calendar grid does not adjust the width dynamically:
> 
>  Bee.O.clock._.Client.Panel.Opera.2024-10-12.15-04-55.mp4

image

**Pull request merged**
